#!/bin/bash
mkdir -p build
lualatex -output-directory=build main.tex   # Run LaTeX to generate the .aux file and other resources
biber build/main   # Run Biber to process the bibliography
lualatex -output-directory=build main.tex   # Run LaTeX again to resolve references
mendex build/main         # Generate the index
lualatex -output-directory=build main.tex   # Final LaTeX pass to finalize the document
# Remove auxiliary files generated by LaTeX
rm -f build/*.aux build/*.bbl build/*.bcf build/*.blg build/*.idx build/*.ilg build/*.ind build/*.lof build/*.log build/*.lot build/*.out build/*.run.xml build/*.toc
